Rails/classroom/config/routes.rb
Rails.application.routes.draw do
  resources :schools
  root 'welcome#index'

  get 'about' => 'welcome#about'
  get 'schools' => 'welcome#schools'

end

Rails/classroom/app/models/school.rb
class School < ActiveRecord::Base
end

Rails/classroom/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Rails/classroom/app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:student, :teacher, :pet)
    end
end

Rails/classroom/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

Rails/classroom/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/classroom/app/helpers/schools_helper.rb
module SchoolsHelper
end

Rails/classroom/app/helpers/welcome_helper.rb
module WelcomeHelper
end

Rails/classroom/app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field form-group">
    <%= f.label :student %><br>
    <%= f.text_field :student, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :teacher %><br>
    <%= f.text_field :teacher, class: "form-control" %>
  </div>
  <div class="field form-group">
    <%= f.label :pet %><br>
    <%= f.number_field :pet, class: "form-control" %>
  </div>
  <div class ="filed form-group">
    <%= f.label "Photo" %><br>
    <%= f.file_field :avatar %>
  </div>
  <div class="actions form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
  <% end %>

Rails/classroom/app/views/schools/edit.html.erb
<h1>Editing School</h1>

<%= render 'form' %>

<%= link_to 'Show', @school %> |
<%= link_to 'Back', schools_path %>

Rails/classroom/app/views/schools/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Listing Schools</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Teacher</th>
      <th>Pet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.student %></td>
        <td><%= school.teacher %></td>
        <td><%= school.pet %></td>
        <td><%= link_to 'Show', school %></td>
        <td><%= link_to 'Edit', edit_school_path(school) %></td>
        <td><%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School', new_school_path %> -->


<h1>My schools wish list</h1>

  <div class="row">
    <% @schools.each do |school| %>
      <div class="col-md-2">
        <div class="panel panel-default">
          <div class="panel-body">
            <h2><%= school.student %></h2>
            <h3><%= school.teacher %></h3>
            <p><strong>Pet: </strong><%= school.pet %></p>

            <div class="btn-group">
            <%= link_to 'Show', school, class: "btn btn-default" %>
           <%= link_to 'Edit', edit_school_path(school), class: "btn btn-default" %>
             <%= link_to 'Destroy', school, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %>
              </div>
        </div>
      </div>
    </div>
  <% end %>

<%= link_to 'New School', new_school_path, class: "btn btn-primary" %>

Rails/classroom/app/views/schools/new.html.erb
<h1>New School</h1>

<%= render 'form' %>

<%= link_to 'Back', schools_path %>

Rails/classroom/app/views/schools/show.html.erb
<!-- <p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @school.student %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @school.teacher %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @school.pet %>
</p> -->

<h1><%= @school.student %>, <%= @school.teacher %></h1>

<%= link_to 'Edit', edit_school_path(@school) %> |
<%= link_to 'Back', schools_path %>